Web/ViewModels/User/ProjectManager/ProjectManagerCreateViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Web.ViewModels.User.ProjectManager
{
    public class ProjectManagerCreateViewModel
    {
        [Display(Name = "First name")]
        [Required(ErrorMessage = "Please enter manager's first name.")]
        [MaxLength(50, ErrorMessage = "Name is too long. Must be under 50 characters.")]
        public string FirstName { get; set; }

        [Display(Name = "Last name")]
        [Required(ErrorMessage = "Please enter manager's last name.")]
        [MaxLength(50, ErrorMessage = "Name is too long. Must be under 50 characters.")]
        public string LastName { get; set; }

        [Display(Name = "e-Mail")]
        [Required(ErrorMessage = "Please enter manager's e-mail address.")]
        [RegularExpression(@"[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?",
            ErrorMessage = "Invalid e-Mail address.")]
        public string Email { get; set; }

        [Display(Name = "User name")]
        [Required(ErrorMessage = "Please enter manager's user name.")]
        [MaxLength(50, ErrorMessage = "Name is too long. Must be under 50 characters.")]
        [Remote("IsPmUsernameTaken", "User")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Please enter manager's password.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Confirm password")]
        [Required(ErrorMessage = "Please enter manager's password.")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Confirmation does not match.")]
        public string ConfirmPassword { get; set; }
    }
}

Web/ViewModels/User/ProjectManager/ProjectManagerDeleteViewModel.cs
using ApplicationCore.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.ViewModels.User.ProjectManager
{
    public class ProjectManagerDeleteViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string IdentityUserId { get; set; }
        public ICollection<Project> Projects { get; set; }
    }
}

Web/ViewModels/User/ProjectManager/ProjectManagerDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Web.ViewModels.User.ProjectManager
{
    public class ProjectManagerDetailsViewModel
    {
        [Display(Name = "Name")]
        public string FullName { get; set; }

        [Display(Name = "User name")]
        public string Username { get; set; }

        [Display(Name = "eMail")]
        public string Email { get; set; }

        [Display(Name = "Number of projects")]
        public int NumberOfProjects { get; set; }
    }
}

Web/Controllers/ProjectController.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using ApplicationCore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Services;
using Web.ViewModels.ProjectManagment.Project;

namespace Web.Controllers
{
    [Authorize(Roles="Admin,Pm")]
    public class ProjectController : Controller
    {
        private readonly ProjectService _projectService;
        private readonly ProjectViewModelService _projectViewModelService;
        public ProjectController(ProjectService projectService, ProjectViewModelService projectViewModelService)
        {
            _projectService = projectService;
            _projectViewModelService = projectViewModelService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _projectViewModelService.GetAllProjects());
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View(await _projectViewModelService.GetCreateViewModel());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProjectCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _projectService.Create(viewModel.Name, viewModel.ManagerId);
                }
                catch (DbUpdateException)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = "Failed to create new project";
                    return View("Error");
                }
                
                return RedirectToAction("Index");
            }
            return View(_projectViewModelService.GetCreateViewModel(viewModel));
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id, string filterTasks)
        {
            if (id == null)
            {
                ViewBag.ErrorMessage = $"Requested page could not be found";
                return View("NotFound");
            }

            ProjectDetailsViewModel viewModel = await _projectViewModelService.GetDetailsViewModel(id.Value, filterTasks);

            if (viewModel == null)
            {
                ViewBag.ErrorMessage = $"Project with id '{id}' not found";
                return View("NotFound");
            }
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                ViewBag.ErrorMessage = $"Requested page could not be found";
                return View("NotFound");
            }

            ProjectEditViewModel viewModel = await _projectViewModelService.GetEditViewModel(id.Value);

            if (viewModel == null)
            {
                ViewBag.ErrorMessage = $"Project with id '{id}' not found";
                return View("NotFound");
            }
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProjectEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _projectService.Edit(viewModel.Id, viewModel.Name, viewModel.ProjectManagerId);
                }
                catch (DbUpdateException)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = "Failed to edit project";
                    return View("Error");
                }

                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                ViewBag.ErrorMessage = $"Requested page could not be found";
                return View("NotFound");
            }

            ProjectDeleteViewModel viewModel = await _projectViewModelService.GetDeleteViewModel(id.Value);

            if (viewModel == null)
            {
                ViewBag.ErrorMessage = $"Project with id '{id}' not found";
                return View("NotFound");
            }
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ProjectDeleteViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _projectService.Delete(viewModel.Id);
                }
                catch (DbUpdateException)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = "Failed to delete project";
                    return View("Error");
                }
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }
    }
}

Web/Controllers/ProjectManagerController.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using ApplicationCore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Services;
using Web.ViewModels.User.ProjectManager;

namespace Web.Controllers
{
    public class ProjectManagerController : Controller
    {
        private readonly IProjectManagerRepository _projectManagerRepository;
        private readonly ProjectManagerViewModelService _projectManagerViewModelService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ProjectManagerService _projectManagerService;

        public ProjectManagerController(IProjectManagerRepository projectManagerRepository,
                                        ProjectManagerViewModelService projectManagerViewModelService,
                                        ProjectManagerService projectManagerService,
                                        UserManager<IdentityUser> userManager)
        {
            _projectManagerRepository = projectManagerRepository;
            _projectManagerViewModelService = projectManagerViewModelService;
            _userManager = userManager;
            _projectManagerService = projectManagerService;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _projectManagerViewModelService.GetIndexViewModel());
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View(new ProjectManagerCreateViewModel());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProjectManagerCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = null;

                try
                {
                    result = await _projectManagerService.Create(
                        viewModel.FirstName, viewModel.LastName, viewModel.UserName, viewModel.Email, viewModel.Password);
                }
                catch (AggregateException ex)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = ex.Message;
                    return View("Error");
                }
                catch (DbUpdateException)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = "Failed to create new project manager";
                    return View("Error");
                }

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Pm")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                ViewBag.ErrorMessage = $"Requested page could not be found";
                return View("NotFound");
            }

            if (User.IsInRole("Pm"))
            {
                if (!(await _projectManagerService.UserHasPermission(User, id)))
                {
                    return RedirectToAction("AccessDenied", "User");
                }
            }

            ProjectManagerDetailsViewModel viewModel = await _projectManagerViewModelService.GetDetailsViewModel(id.Value);

            if (viewModel == null)
            {
                ViewBag.ErrorMessage = $"Project manager with id '{id}' not found";
                return View("NotFound");
            }
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Pm")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                ViewBag.ErrorMessage = $"Requested page could not be found";
                return View("NotFound");
            }

            if (User.IsInRole("Pm"))
            {
                if (!(await _projectManagerService.UserHasPermission(User, id)))
                {
                    return RedirectToAction("AccessDenied", "User");
                }
            }

            ProjectManagerEditViewModel viewModel = await _projectManagerViewModelService.GetEditViewModel(id.Value);

            if (viewModel == null)
            {
                ViewBag.ErrorMessage = $"Project manager with id '{id}' not found";
                return View("NotFound");
            }
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProjectManagerEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                ProjectManager manager = await _projectManagerRepository.GetByIdAsync(viewModel.Id);

                if (manager == null)
                {
                    ViewBag.ErrorMessage = $"Project manager with id '{viewModel.Id}' not found";
                    return View("NotFound");
                }

                IdentityResult result = null;

                try
                {
                    result = await _projectManagerService.Edit(User, viewModel.Id, viewModel.FirstName, viewModel.LastName, 
                        viewModel.UserName, viewModel.Email, viewModel.Password);
                }
                catch (AggregateException ex)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = ex.Message;
                    return View("Error");
                }
                catch (DbUpdateException)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = "Failed to edit project manager";
                    return View("Error");
                }

                if (result.Succeeded)
                {
                    return RedirectToAction("Details", new { Id = viewModel.Id });
                }
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                ViewBag.ErrorMessage = $"Requested page could not be found";
                return View("NotFound");
            }

            ProjectManagerDeleteViewModel viewModel = await _projectManagerViewModelService.GetDeleteViewModel(id);

            if (viewModel == null)
            {
                ViewBag.ErrorMessage = $"Project manager with id '{id}' not found";
                return View("NotFound");
            }
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ProjectManagerDeleteViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                ProjectManager manager = await _projectManagerRepository.GetByIdAsync(viewModel.Id);

                if (manager == null)
                {
                    ViewBag.ErrorMessage = $"Project manager with id '{viewModel.Id}' not found";
                    return View("NotFound");
                }

                IdentityResult result = null;

                try
                {
                    result = await _projectManagerService.Delete(manager.Id);
                }
                catch (AggregateException ex)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = ex.Message;
                    return View("Error");
                }
                catch (DbUpdateException)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = "Failed to delete project manager";
                    return View("Error");
                }

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(viewModel);
        }
    }
}

Web/Views/ProjectManager/Create.cshtml
@model Web.ViewModels.User.ProjectManager.ProjectManagerCreateViewModel

@{
    ViewBag.Title = "Create new project manager";
}

<h3>Create new project manager</h3>

<div class="row">
    <div class="col-md-12">
        <form asp-controller="ProjectManager" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <label asp-for="FirstName"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <label asp-for="LastName"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <label asp-for="UserName"></label>
                    <input asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <label asp-for="Password"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <label asp-for="ConfirmPassword"></label>
                    <input asp-for="ConfirmPassword" class="form-control" />
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary">
                <a asp-controller="ProjectManager" asp-action="Index">Cancel</a>
            </div>
        </form>
    </div>
</div>

Web/Views/ProjectManager/Delete.cshtml
@model Web.ViewModels.User.ProjectManager.ProjectManagerDeleteViewModel

@{
    ViewBag.Title = "Delete project manager";
}

<h3>Delete project manager</h3>

@if (Model.Projects.Count != 0)
{
    <h4>@Model.Name manages these projects:</h4>
    foreach (var project in Model.Projects)
    {
        <h5>@project.Name</h5>
    }
    <br />
    <h4>Please reassign projects to another manager and then try again</h4>

    <a asp-controller="ProjectManager" asp-action="Index">Back</a>
}
else
{
    <h4>@Model.Name</h4>
    <h4>Are you sure?</h4>
    <br />
    <form asp-controller="ProjectManager" asp-action="Delete">
        <input asp-for="Id" hidden />
        <input asp-for="IdentityUserId" hidden />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-controller="ProjectManager" asp-action="Index">Cancel</a>
    </form>
}

Web/Views/ProjectManager/Details.cshtml
@model Web.ViewModels.User.ProjectManager.ProjectManagerDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h3>Details</h3>


<dl class="row">
    <dt class="col-sm-2">
        <label asp-for="@Model.FullName"></label>
    </dt>
    <dd class="col-sm-10">
        @Model.FullName
    </dd>
    <dt class="col-sm-2">
        <label asp-for="@Model.Username"></label>
    </dt>
    <dd class="col-sm-10">
        @Model.Username
    </dd>
    <dt class="col-sm-2">
        <label asp-for="@Model.Email"></label>
    </dt>
    <dd class="col-sm-10">
        @Model.Email
    </dd>
    <dt class="col-sm-2">
        <label asp-for="@Model.NumberOfProjects"></label>
    </dt>
    <dd class="col-sm-10">
        @Model.NumberOfProjects
    </dd>
</dl>

<div class="modal-footer">
    @if (User.IsInRole("Admin"))
    {
        <a asp-controller="ProjectManager" asp-action="Index">Back to list</a>
    }
    else if (User.IsInRole("Pm"))
    {
        <a asp-controller="Project" asp-action="Index">Back</a>
    }
</div>

Web/Views/ProjectManager/Edit.cshtml
@model Web.ViewModels.User.ProjectManager.ProjectManagerEditViewModel

@{
    ViewBag.Title = "Edit project manager";
}

<h3>Edit project manager</h3>

<div class="row">
    <div class="col-md-12">
        <form asp-controller="ProjectManager" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" hidden />
            <div class="form-group row">
                <div class="col-sm-5">
                    <label asp-for="FirstName"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <label asp-for="LastName"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <label asp-for="UserName"></label>
                    <input asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
            </div>
            @if (User.IsInRole("Pm"))
            {
                <div class="form-group row">
                    <div class="col-sm-5">
                        <label asp-for="Password"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-5">
                        <label asp-for="ConfirmPassword"></label>
                        <input asp-for="ConfirmPassword" class="form-control" />
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary">
                    <a asp-controller="Home" asp-action="Index">Cancel</a>
                </div>
            }
            else if (User.IsInRole("Admin"))
            {
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary">
                    <a asp-controller="ProjectManager" asp-action="Index">Cancel</a>
                </div>
            }
        </form>
    </div>
</div>

Web/Views/ProjectManager/Index.cshtml
@model IEnumerable<ApplicationCore.Entities.ProjectManager>

@{
    ViewBag.Title = "Project managers";
}

<h3>Project managers</h3>

<div class="mt-3">
     <a asp-controller="ProjectManager" asp-action="Create">Create new project manager</a>
</div>

<table class="table mt-3">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                No. of projects
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var pm in Model)
        {
            <tr>
                <td>
                     <span>@pm.FullName</span>
                </td>
                <td>
                    @if (pm.Projects != null)
                    {
                        <span>@pm.Projects.Count</span>
                    }
                    else
                    {
                        <span>0</span>
                    }
                </td>
                <td>
                    <a asp-controller="ProjectManager" asp-action="Details" asp-route-id="@pm.Id">Details</a> |
                    <a asp-controller="ProjectManager" asp-action="Edit" asp-route-id="@pm.Id">Edit</a> |
                    <a asp-controller="ProjectManager" asp-action="Delete" asp-route-id="@pm.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>