Web/ViewModels/ProjectManagment/Task/TaskCreateViewModel.cs
using ApplicationCore.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Web.ViewModels.ProjectManagment.Task
{
    public class TaskCreateViewModel
    {
        [Required(ErrorMessage = "Task must have a name.")]
        [MaxLength(50, ErrorMessage = "Task name must be under 50 characters long.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Task must have a decription.")]
        [MaxLength(300, ErrorMessage = "Task description must be under 300 characters long.")]
        [MinLength(10, ErrorMessage = "Task description must be at least 10 characters.")]
        public string Description { get; set; }

        public int Progress { get; set; }

        public TaskStatus Status { get; set; }

        [Required(ErrorMessage = "Task must have a deadline.")]
        [DataType(DataType.Date)]
        public DateTime Deadline { get; set; }

        public int ProjectId { get; set; }

        public int? DeveloperId { get; set; }

        [Display(Name = "Available developers")]
        public SelectList Developers { get; set; }
    }
}

Web/ViewModels/ProjectManagment/Task/TaskDeleteViewModel.cs
using ApplicationCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Web.ViewModels.ProjectManagment.Task
{
    public class TaskDeleteViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ProjectTaskStatus Status { get; set; }
        public int ProjectId { get; set; }
        public int? DeveloperId { get; set; }
    }
}

Web/ViewModels/ProjectManagment/Task/TaskDetailsViewModel.cs
using ApplicationCore;
using ApplicationCore.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Web.ViewModels.ProjectManagment.Task
{
    public class TaskDetailsViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Progress { get; set; }
        public ProjectTaskStatus Status { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Deadline { get; set; }
        public int ProjectId { get; set; }
        public int? DeveloperId { get; set; }

        [Display(Name = "Developer assigned")]
        public string DeveloperName { get; set; }
    }
}

Web/Controllers/DeveloperController.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using ApplicationCore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Services;
using Web.ViewModels.User.Developer;

namespace Web.Controllers
{
    public class DeveloperController : Controller
    {
        private readonly DeveloperViewModelService _developerViewModelService;
        private readonly DeveloperService _developerService;
        private readonly IDeveloperRepository _developerRepository;
        private readonly UserManager<IdentityUser> _userManager;

        public DeveloperController(DeveloperViewModelService developerViewModelService,
                                   DeveloperService developerService,
                                   IDeveloperRepository developerRepository,
                                   UserManager<IdentityUser> userManager)
        {
            _developerViewModelService = developerViewModelService;
            _developerService = developerService;
            _developerRepository = developerRepository;
            _userManager = userManager;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _developerViewModelService.GetIndexViewModel());
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View(new DeveloperCreateViewModel());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DeveloperCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = null;

                try
                {
                    result = await _developerService.Create(
                        viewModel.FirstName, viewModel.LastName, viewModel.UserName, viewModel.Email, viewModel.Password);
                }
                catch (AggregateException ex)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = ex.Message;
                    return View("Error");
                }
                catch (DbUpdateException)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = "Failed to create new developer";
                    return View("Error");
                }

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Dev")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                ViewBag.ErrorMessage = $"Requested page could not be found";
                return View("NotFound");
            }

            if (User.IsInRole("Dev"))
            {
                if (!(await _developerService.UserHasPermission(User, id)))
                {
                    return RedirectToAction("AccessDenied", "User");
                }
            }

            DeveloperDetailsViewModel viewModel = await _developerViewModelService.GetDetailsViewModel(id.Value);

            if (viewModel == null)
            {
                ViewBag.ErrorMessage = $"Developer with id '{id}' not found";
                return View("NotFound");
            }
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Dev")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                ViewBag.ErrorMessage = $"Requested page could not be found";
                return View("NotFound");
            }

            if (User.IsInRole("Dev"))
            {
                if (!(await _developerService.UserHasPermission(User, id)))
                {
                    return RedirectToAction("AccessDenied", "User");
                }
            }

            DeveloperEditViewModel viewModel = await _developerViewModelService.GetEditViewModel(id.Value);

            if (viewModel == null)
            {
                ViewBag.ErrorMessage = $"Developer with id '{id}' not found";
                return View("NotFound");
            }
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(DeveloperEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Developer developer = await _developerRepository.GetByIdAsync(viewModel.Id);

                if (developer == null)
                {
                    ViewBag.ErrorMessage = $"Developer with id '{viewModel.Id}' not found";
                    return View("NotFound");
                }

                IdentityResult result = null;

                try
                {
                    result = await _developerService.Edit(User, viewModel.Id, viewModel.FirstName, viewModel.LastName,
                        viewModel.UserName, viewModel.Email, viewModel.Password);
                }
                catch (AggregateException ex)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = ex.Message;
                    return View("Error");
                }
                catch (DbUpdateException)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = "Failed to edit developer";
                    return View("Error");
                }

                if (result.Succeeded)
                {
                    return RedirectToAction("Details", new { Id = viewModel.Id });
                }
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                ViewBag.ErrorMessage = $"Requested page could not be found";
                return View("NotFound");
            }

            DeveloperDeleteViewModel viewModel = await _developerViewModelService.GetDeleteViewModel(id.Value);

            if (viewModel == null)
            {
                ViewBag.ErrorMessage = $"Developer with id '{id}' not found";
                return View("NotFound");
            }
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(DeveloperDeleteViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Developer developer = await _developerRepository.GetByIdAsync(viewModel.Id);

                if (developer == null)
                {
                    ViewBag.ErrorMessage = $"Developer with id '{viewModel.Id}' not found";
                    return View("NotFound");
                }

                IdentityResult result = null;

                try
                {
                    result = await _developerService.Delete(developer.Id);
                }
                catch (AggregateException ex)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = ex.Message;
                    return View("Error");
                }
                catch (DbUpdateException)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = "Failed to delete developer";
                    return View("Error");
                }

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Tasks(int? id)
        {
            if (id == null)
            {
                ViewBag.ErrorMessage = $"Requested page could not be found";
                return View("NotFound");
            }

            DeveloperTasksViewModel viewModel = await _developerViewModelService.GetTasksViewModel(id.Value);

            if (viewModel == null)
            {
                ViewBag.ErrorMessage = $"Developer with id '{id}' not found";
                return View("NotFound");
            }
            return View(viewModel);
        }
    }
}

Web/Controllers/ProjectController.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using ApplicationCore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Services;
using Web.ViewModels.ProjectManagment.Project;

namespace Web.Controllers
{
    [Authorize(Roles="Admin,Pm")]
    public class ProjectController : Controller
    {
        private readonly ProjectService _projectService;
        private readonly ProjectViewModelService _projectViewModelService;
        public ProjectController(ProjectService projectService, ProjectViewModelService projectViewModelService)
        {
            _projectService = projectService;
            _projectViewModelService = projectViewModelService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _projectViewModelService.GetAllProjects());
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View(await _projectViewModelService.GetCreateViewModel());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProjectCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _projectService.Create(viewModel.Name, viewModel.ManagerId);
                }
                catch (DbUpdateException)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = "Failed to create new project";
                    return View("Error");
                }
                
                return RedirectToAction("Index");
            }
            return View(_projectViewModelService.GetCreateViewModel(viewModel));
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id, string filterTasks)
        {
            if (id == null)
            {
                ViewBag.ErrorMessage = $"Requested page could not be found";
                return View("NotFound");
            }

            ProjectDetailsViewModel viewModel = await _projectViewModelService.GetDetailsViewModel(id.Value, filterTasks);

            if (viewModel == null)
            {
                ViewBag.ErrorMessage = $"Project with id '{id}' not found";
                return View("NotFound");
            }
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                ViewBag.ErrorMessage = $"Requested page could not be found";
                return View("NotFound");
            }

            ProjectEditViewModel viewModel = await _projectViewModelService.GetEditViewModel(id.Value);

            if (viewModel == null)
            {
                ViewBag.ErrorMessage = $"Project with id '{id}' not found";
                return View("NotFound");
            }
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProjectEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _projectService.Edit(viewModel.Id, viewModel.Name, viewModel.ProjectManagerId);
                }
                catch (DbUpdateException)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = "Failed to edit project";
                    return View("Error");
                }

                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                ViewBag.ErrorMessage = $"Requested page could not be found";
                return View("NotFound");
            }

            ProjectDeleteViewModel viewModel = await _projectViewModelService.GetDeleteViewModel(id.Value);

            if (viewModel == null)
            {
                ViewBag.ErrorMessage = $"Project with id '{id}' not found";
                return View("NotFound");
            }
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ProjectDeleteViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _projectService.Delete(viewModel.Id);
                }
                catch (DbUpdateException)
                {
                    ViewBag.ErrorTitle = "Error";
                    ViewBag.ErrorMessage = "Failed to delete project";
                    return View("Error");
                }
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }
    }
}

Web/Views/Task/Create.cshtml
@model Web.ViewModels.ProjectManagment.Task.TaskCreateViewModel

@{
    ViewBag.Title = "Create new task";
}

<h3>Create new task</h3>

<div class="row">
    <div class="col-md-12">
        <form asp-controller="Task" asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="ProjectId" hidden/>
            <div class="form-group row">
                <div class="col-sm-5">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <label asp-for="Description"></label>
                    <textarea rows="7" style="resize:none" asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <label asp-for="Deadline"></label>
                    <input asp-for="Deadline"  class="form-control" />
                    <span asp-validation-for="Deadline" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <label asp-for="Developers"></label>
                    <select asp-for="DeveloperId" class="form-control" asp-items="@Model.Developers">
                        <option value="">-- Select --</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary">
                <a asp-controller="Project" asp-action="Details" asp-route-id="@Model.ProjectId">Cancel</a>
            </div>
        </form>
    </div>
</div>

Web/Views/Task/Delete.cshtml
@model Web.ViewModels.ProjectManagment.Task.TaskDeleteViewModel

@{ 
    ViewBag.Title = "Delete task";
}

<h3>Delete task. Are you sure?</h3>

@if (Model.Status != ApplicationCore.ProjectTaskStatus.Finished)
{
    <h4>Task is not finished.</h4>
}

<dl class="row">
    <dt class="col-sm-2">
        <label asp-for="@Model.Name"></label>
    </dt>
    <dd class="col-sm-10">
        @Model.Name
    </dd>
    <dt class="col-sm-2">
        <label asp-for="@Model.Description"></label>
    </dt>
    <dd class="col-sm-10">
        @Model.Description
    </dd>
    <dt class="col-sm-2">
        <label asp-for="@Model.Status"></label>
    </dt>
    <dd class="col-sm-10">
        @if (Model.Status == ApplicationCore.ProjectTaskStatus.InProgress)
        {
            <span>In progress</span>
        }
        else
        {
            <span>@Model.Status</span>
        }
    </dd>
</dl>

<form asp-controller="Task" asp-action="Delete">
    <input asp-for="ProjectId" hidden/>
    <input asp-for="DeveloperId" hidden/>
    <input type="submit" value="Delete" class="btn btn-danger">
    <a asp-controller="Project" asp-action="Details" asp-route-id="@Model.ProjectId">Cancel</a>
</form>

Web/Views/Task/Details.cshtml
@model Web.ViewModels.ProjectManagment.Task.TaskDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h3>Details</h3>


<dl class="row">
    <dt class="col-sm-2">
        <label asp-for="@Model.Name"></label>
    </dt>
    <dd class="col-sm-10">
        @Model.Name
    </dd>
    <dt class="col-sm-2">
        <label asp-for="@Model.Description"></label>
    </dt>
    <dd class="col-sm-10">
        @Model.Description
    </dd>
    <dt class="col-sm-2">
        <label asp-for="@Model.Deadline"></label>
    </dt>
    <dd class="col-sm-10">
        @Model.Deadline.Day - @Model.Deadline.Month - @Model.Deadline.Year
    </dd>
    <dt class="col-sm-2">
        <label asp-for="@Model.Progress"></label> (%)
    </dt>
    <dd class="col-sm-10">
        @Model.Progress
    </dd>
    <dt class="col-sm-2">
        <label asp-for="@Model.Status"></label>
    </dt>
    <dd class="col-sm-10">
        @if (Model.Status == ApplicationCore.ProjectTaskStatus.InProgress)
        {
            <span>In progress</span>
        }
        else
        {
            <span>@Model.Status </span>
        }
    </dd>
    <dt class="col-sm-2">
        <label asp-for="@Model.DeveloperName"></label>
    </dt>
    <dd class="col-sm-10">
        @if (Model.DeveloperName != null)
        {
            <h6>@Model.DeveloperName</h6>
        }
        else
        {
            <h6>No developer assigned</h6>
        }
    </dd>
</dl>

<div class="modal-footer">
    @if (User.IsInRole("Dev"))
    {
        <a asp-controller="Developer" asp-action="Tasks" asp-route-id="@Model.DeveloperId">Back</a>
    }
    else
    {
        <a asp-controller="Project" asp-action="Details" asp-route-id="@Model.ProjectId">Back to project</a>
    }
</div>

Web/Views/Task/Edit.cshtml
@model Web.ViewModels.ProjectManagment.Task.TaskEditViewModel

@{
    ViewBag.Title = "Edit task";
}

<h3>Edit task</h3>

@if (User.IsInRole("Dev"))
{
    <div class="row">
        <div class="col-md-12">
            <form asp-controller="Task" asp-action="Edit" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="Id" hidden />
                <input asp-for="ProjectId" hidden />
                <input asp-for="Name" hidden />
                <input asp-for="Deadline" hidden />
                <input asp-for="DeveloperId" hidden />
                <div class="form-group row">
                    <div class="col-sm-5">
                        <label asp-for="Description"></label>
                        <textarea rows="7" style="resize:none" asp-for="Description" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-5">
                        <label asp-for="Progress"></label>
                        <div class="custom-radio">
                            <input type="radio" value="0" asp-for="Progress" class="mr-2" />0 |
                            <input type="radio" value="20" asp-for="Progress" class="mr-2" />20 |
                            <input type="radio" value="40" asp-for="Progress" class="mr-2" />40 |
                            <input type="radio" value="60" asp-for="Progress" class="mr-2" />60 |
                            <input type="radio" value="80" asp-for="Progress" class="mr-2" />80 |
                            <input type="radio" value="100" asp-for="Progress" class="mr-2" />100
                        </div>
                        <span asp-validation-for="Progress" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary">
                    <a asp-controller="Developer" asp-action="Tasks" asp-route-id="@Model.DeveloperId">Cancel</a>
                </div>
            </form>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-md-12">
            <form asp-controller="Task" asp-action="Edit" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="Id" hidden />
                <input asp-for="ProjectId" hidden />
                <div class="form-group row">
                    <div class="col-sm-5">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-5">
                        <label asp-for="Description"></label>
                        <textarea rows="7" style="resize:none" asp-for="Description" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-5">
                        <label asp-for="Deadline"></label>
                        <input asp-for="Deadline" class="form-control" />
                        <span asp-validation-for="Deadline" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-5">
                        <label asp-for="Progress"></label>
                        <div class="custom-radio">
                            <input type="radio" value="0" asp-for="Progress" class="mr-2" />0 |
                            <input type="radio" value="20" asp-for="Progress" class="mr-2" />20 |
                            <input type="radio" value="40" asp-for="Progress" class="mr-2" />40 |
                            <input type="radio" value="60" asp-for="Progress" class="mr-2" />60 |
                            <input type="radio" value="80" asp-for="Progress" class="mr-2" />80 |
                            <input type="radio" value="100" asp-for="Progress" class="mr-2" />100
                        </div>
                        <span asp-validation-for="Progress" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-5">
                        <label asp-for="Developers"></label>
                        <select asp-for="DeveloperId" class="form-control" asp-items="@Model.Developers">
                            <option value="">-- Select --</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary">
                    <a asp-controller="Project" asp-action="Details" asp-route-id="@Model.ProjectId">Cancel</a>
                </div>
            </form>
        </div>
    </div>
}